# Main terminal settings
[main]

# Set login shell
shell=bash

# Font type and size
font=monospace:size=11

# Set window padding: left, top, right, bottom
pad=25x10x25x25

# Color scheme
[colors-dark]

# Set background transparency
#alpha=1
alpha=0.68
#alpha=0.34
#alpha=0

# Base background and text colors
background=010305 # blue black
foreground=8a97bf # slate blue 

# Normal ANSI color palette
regular0=010305 # blue black
regular1=819bdc # light blue 
regular2=a799cd # pale light purple 
regular3=515568 # pale matte purple 
regular4=8a97bf # slate blue X
regular5=ddddff # pale lavender 
regular6=c7829d # rose pink 
regular7=b0bacd # light gray blue 

# Bright ANSI color palette
bright0=4e5660 # bright light charcoal gray
bright1=819bdc # bright light blue 
bright2=a799cd # bright pale light purple 
bright3=515568 # bright pale matte purple 
bright4=8a97bf # bright slate blue 
bright5=ddddff # bright pale lavender 
bright6=c7829d # bright rose pink 
bright7=ffffff # white 

# Cursor appearance
[cursor]

# Use an underline cursor
style=underline

# Enable cursor blinking
blink=yes

# Blink every 500 ms
blink-rate=500

# Hide cursor when window is unfocused
unfocused-style=none
